production deploy
CareerBuddyTalent/candidate pull request #37
Opened 2023-06-18 06:02 UTC by onyijne

2023-06-18 06:15 UTC, onyijne reviewed
This domain `.careerbuddy-landing.netlify.app` will break in production.
I will suggest domain is written in env file so production value will be different from staging and also different from local.
`FRONTEND_URL=.localhost.com` for local env
 file
`FRONTEND_URL=.careerbuddy-landing.netlify.app` for staging env file
`FRONTEND_URL=.thecareerbuddy.com`  for production env file

2023-06-18 06:27 UTC, onyijne reviewed
Line 114 will only trigger a notification if check fails, but won't stop the process.
Also, the `check.length == 2` is redundant in line 87 and 96. Doing just 
```js
if (

2023-06-18 06:35 UTC, onyijne commented on src/utils/helper.js
This domain .careerbuddy-landing.netlify.app will break in production.
I will suggest domain is written in env file so production value will be different from staging and also different from local.
FRONTEND_URL=.localhost.com for local env
file
FRONTEND_URL=.careerbuddy-landing.netlify.app for staging env file
FRONTEND_URL=.thecareerbuddy.com for production env file

2023-06-18 06:37 UTC, onyijne commented on src/views/auth/Onboard.vue
Line 114 will only trigger a notification if check fails, but won't stop the process.
Also, the check.length == 2 is redundant in line 87 and 96. Doing just

if (check.length != 2 && ....) 
would be fine.

2023-06-18 06:48 UTC, careerbuddytech requested changes
isValidLinkedIn should return true or false, and handleEvent should proceed or terminate based on the returned value in `views/auth/onboard.vue`.

`utils/helpers.js` also need to be updated to avoid the [cookie domain](https://github.com/CareerBuddyTalent/candidate/pull/37/files#r1233206389) breaking in production.

2023-06-20 20:09 UTC, careerbuddytech approved these changes

2023-06-20 20:09 UTC, merged